force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The deadline of the project</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day that the project must start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick Off</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Required_Role__c/Required_Role__c.object-meta.xml
<CustomObject>
    <label>Required Role</label>
    <nameField>
        <label>Required Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Sold_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Required_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Required_Role__c/fields/TotalCoverage__c.field-meta.xml
<CustomField>
    <fullName>TotalCoverage__c</fullName>
    <description>RollUp</description>
    <label>TotalCoverage</label>
    <summarizedField>Resource_Allocation__c.Total_Hours__c</summarizedField>
    <summaryForeignKey>Resource_Allocation__c.Required_Role__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/Resource_Allocation__c.object-meta.xml
<CustomObject>
    <label>Resource Allocation</label>
    <nameField>
        <label>Resource Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/fields/Required_Role__c.field-meta.xml
<CustomField>
    <fullName>Required_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Role</label>
    <referenceTo>Required_Role__c</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Resources__c.field-meta.xml
<CustomField>
    <fullName>Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AllocationFilter.cls
public with sharing class AllocationFilter {
    public static List<Required_Role__c> getRequiredRoles(Id projectID) {
        List<Required_Role__c> requiredRoles = [
            SELECT Role__c, Quantity__c, TotalCoverage__c, Project__r.Start_Date__c, Project__r.End_Date__c
            FROM Required_Role__c
            WHERE Project__c =: projectID];

            return requiredRoles;
    }

    public static List<User> findUsersWithRequiredRoles(List<Required_Role__c> requiredRoles) {
        List<String> roles = new List<String>();

        for(Required_Role__c requiredRole : requiredRoles){
            roles.add(requiredRole.Role__c);
        }

        List<User> resourcesMeetingRequirements = [SELECT FirstName, LastName, UserRole.Name 
        FROM User 
        WHERE UserRole.Name
        IN: roles];

        return resourcesMeetingRequirements;
    }


    public static List<User> checkAllocatedResources(Id projectID){

        List<Required_Role__c> requiredRoleWithProjectDates = getRequiredRoles(projectID);
        List<User> resources = findUsersWithRequiredRoles(requiredRoleWithProjectDates);

        List<Id> rosurcesIdsToFilter = new List<Id>(); //(id1, id2)
        
        for(User resource : resources){
            rosurcesToFilter.add(resource.Id);
        }
        
        //recursos con fechas para comparar
        //[pepeFechasP, MAriaFechas, pepeFechaP2]
        List<Resource_Allocation__c> resourcesAllocated = [SELECT StartDate__c, EndDate__c, Resources__c FROM Resource_Allocation__c WHERE Resource__c IN: rosurcesToFilter AND Required_Role__r.Project__r.Status__c != 'Completed'] //(id1)

        //mapa key: userId, value: lista de fechas de proyectos (resourcesAllocated)
        //mapa -> {pepeId : [PepeFecha1, PepeFecha2]
        //        mariaIdI: [mariaFecha]}
        Map<Id, List<Resource_Allocation__c>> resourceAllocationsByUserId = new Map<Id, List<Resource_Allocation__c>>;
        
        //armado de mapa con userId : lista de allocation vacia.
        for(Id userId : rosurcesIdsToFilter){
            resourceAllocationsByUserId.put(userId, new List<Resource_Allocation__c>());
        }

        for(Resource_Allocation__c resourceAllocated : resourcesAllocated){
            if(resourceAllocationsByUserId.containsKey(resourceAllocated.Resources__c)){
                resourceAllocationsByUserId.get(resourceAllocated.Resources__c).add(resourceAllocated);
            }
        }
        
        Date ProjectStartDate = requiredRoleWithProjectDates[0].Start_Date__c;
        Date ProjectEndDate = requiredRoleWithProjectDates[0].End_Date__c;

        Set<Id> filteredResourcesIds = new List<Id>(); //guardar users Ids disponibles en la fecha de project

        for(Id userId : resourceAllocationsByUserId.keySet()){
            if(resourceAllocationsByUserId.get(userID).size > 0){
                Boolean available = true;
                for(Resource_Allocation__c resourceAllocatedDates : resourceAllocationsByUserId.get(userID)){
 
                    if( ( resourceAllocatedDates.StartDate__c < ProjectStartDate && ( resourceAllocatedDates.EndDate__c < ProjectEndDate || resourceAllocatedDates.EndDate__c < ProjectStartDate ) ) || resourceAllocatedDates.StartDate__c > ProjectEndDate ){
                        continue;
                    }else{
                        available = false;
                        break;
                    }
                }
                if(available){
                    filteredResourcesIds.add(userId);
                }
            }else{
                filteredResourcesIds.add(userId);
            }
        }

        //query para buscar los usurios y devolverlos en una lista de user
        List<User> usersAvailables = [SELECT FirstName, LastName, UserRole.Name 
        FROM User 
        WHERE Id
        IN: filteredResourcesIds];

        return usersAvailables;
    }

    public static List<User> filterUserByRole(Id projectId, String roleName){
        List<User> users = checkAllocatedResources(projectId);
        
        List<User> usersByRol = new List<User>();
        for(User user : users){
            if(user.UserRole.Name == roleName){
                usersByRol.add(user);
            }
        }

        return usersByRol;
    }
}