force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The deadline of the project</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day that the project must start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick Off</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Required_Role__c/Required_Role__c.object-meta.xml
<CustomObject>
    <label>Required Role</label>
    <nameField>
        <label>Required Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Sold_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Required_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Required_Role__c/fields/TotalCoverage__c.field-meta.xml
<CustomField>
    <fullName>TotalCoverage__c</fullName>
    <description>RollUp</description>
    <label>TotalCoverage</label>
    <summarizedField>Resource_Allocation__c.Total_Hours__c</summarizedField>
    <summaryForeignKey>Resource_Allocation__c.Required_Role__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/Resource_Allocation__c.object-meta.xml
<CustomObject>
    <label>Resource Allocation</label>
    <nameField>
        <label>Resource Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/fields/Required_Role__c.field-meta.xml
<CustomField>
    <fullName>Required_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Role</label>
    <referenceTo>Required_Role__c</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Resources__c.field-meta.xml
<CustomField>
    <fullName>Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AllocationFilterController.cls
public with sharing class AllocationFilterController {
    //devuelve una lista con RequiredRole Objects para acceder a los roles requeridos y fechas de proyecto
    @AuraEnabled(cacheable=true)
    public static List<Required_Role__c> getRequiredRoles(Id projectID) {
        List<Required_Role__c> requiredRoles = [
            SELECT Role__c, Quantity__c, TotalCoverage__c, Project__r.Start_Date__c, Project__r.End_Date__c
            FROM Required_Role__c
            WHERE Project__c =: projectID];

            return requiredRoles;
    }

    // a partir de un rol dado trae una lista de usuarios con ese rol
    public static List<User> findUsersWithRequiredRoles(String roleName) {

        List<User> resourcesMeetingRequirements = [SELECT FirstName, LastName, UserRole.Name 
        FROM User 
        WHERE UserRole.Name =: roleName];

        return resourcesMeetingRequirements;
    }

    //recibe el projectId y a partir de un rol dado busca los usuarios y devuelve los disponibles para su fecha de start y end 
    @AuraEnabled(cacheable=true)
    public static List<User> checkAllocatedResources(Id projectID, String roleName){
        List<Required_Role__c> requiredRoleWithProjectDates = getRequiredRoles(projectID);
        List<User> resources = findUsersWithRequiredRoles(roleName);

        List<Id> resourcesIdsToFilter = new List<Id>(); //(id1, id2)
        
        for(User resource : resources){
            resourcesIdsToFilter.add(resource.Id);
        }
        
        Date ProjectStartDate = requiredRoleWithProjectDates[0].Project__r.Start_Date__c;
        Date ProjectEndDate = requiredRoleWithProjectDates[0].Project__r.End_Date__c;

        //tenemos los no disponibles = con intersecciones
        List<Resource_Allocation__c> resourcesAllocated = [SELECT StartDate__c, EndDate__c, Resources__c FROM Resource_Allocation__c WHERE Resources__c IN: resourcesIdsToFilter AND Required_Role__r.Project__r.Status__c != 'Completed' AND EndDate__c >:  ProjectStartDate AND StartDate__c <: ProjectEndDate];

        Map<Id, List<Resource_Allocation__c>> resourceAllocationsByUserId = new Map<Id, List<Resource_Allocation__c>>();
        
        //armado de mapa con userId : lista de allocation vacia.
        for(Id userId : resourcesIdsToFilter){
            resourceAllocationsByUserId.put(userId, new List<Resource_Allocation__c>());
        }

        for(Resource_Allocation__c resourceAllocated : resourcesAllocated){
            if(resourceAllocationsByUserId.containsKey(resourceAllocated.Resources__c)){
                resourceAllocationsByUserId.get(resourceAllocated.Resources__c).add(resourceAllocated);
            }
        }
        
        Set<Id> filteredResourcesIds = new Set<Id>(); //guardar users Ids disponibles en la fecha de project

        for(Id userId : resourceAllocationsByUserId.keySet()){
            if(resourceAllocationsByUserId.get(userID).size() == 0){
                filteredResourcesIds.add(userId);                
            }
        }

        //query para buscar los usurios y devolverlos en una lista de user
        List<User> usersAvailables = [SELECT FirstName, LastName, UserRole.Name 
        FROM User 
        WHERE Id
        IN: filteredResourcesIds];

        return usersAvailables;
    }
    
}