force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The deadline of the project</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day that the project must start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick Off</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Required_Role__c/Required_Role__c.object-meta.xml
<CustomObject>
    <label>Required Role</label>
    <nameField>
        <label>Required Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Sold_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/Resource_Allocation__c.object-meta.xml
<CustomObject>
    <label>Resource Allocation</label>
    <nameField>
        <label>Resource Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/fields/Required_Role__c.field-meta.xml
<CustomField>
    <fullName>Required_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Role</label>
    <referenceTo>Required_Role__c</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Resources__c.field-meta.xml
<CustomField>
    <fullName>Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ResourceAllocationHelper.cls
public with sharing class ResourceAllocationHelper {
    public static void onbeforeInsert(List<Resource_Allocation__c> newResourcesData) {
        //validar que las fechas asignadas no sean no se salgan del rango de  fechas del proyecto
        Required_Role__c projectData = [SELECT Project__r.Start_Date__c, Project__r.End_Date__c FROM Required_Role__c WHERE Id  =: newResourcesData[0].Required_Role__c LIMIT 1];

        Date startProjectDate = projectData.Project__r.Start_Date__c;
        Date endProjectDate = projectData.Project__r.End_Date__c;

        for(Resource_Allocation__c resource : newResourcesData){
            if(resource.StartDate__c < startProjectDate || resource.StartDate__c > endProjectDate || resource.EndDate__c < startProjectDate || resource.EndDate__c > endProjectDate){
                resource.addError('Either the Start Date or End Date you defined for a Resource is out of the project date range');
            }
        }

        //evitar insersion manual de recursos en tabla resource allocation validando que el recurso no este alocado en ningun otro proyecto y haga intersección en el actual
        Set<Id> usersIds = new Set<Id>();
        for(Resource_Allocation__c allocation : newResourcesData){
            usersIds.add(allocation.Resources__c);
        }

        List<Resource_Allocation__c> allocationsToCheck = [SELECT StartDate__c, EndDate__c, Resources__c FROM Resource_Allocation__c WHERE Resources__c IN: usersIds AND Required_Role__r.Project__r.Status__c != 'Completed' AND EndDate__c >:  startProjectDate AND StartDate__c <: endProjectDate];

        for(Resource_Allocation__c allocation : allocationsToCheck){
            for(Resource_Allocation__c newInsert : newResourcesData){
                if(allocation.Resources__c == newInsert.Resources__c){
                    newInsert.addError('Either the Start Date or End Date you defined for a Resource is out of the project date range');
                }
            }
        }

    }
}