force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Manager in charge of the opportunity</description>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <description>Total hours per rol in Opportunity Line Item</description>
    <label>Total Hours</label>
    <summarizedField>Opportunity_Line_Item__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Line_Item__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The deadline of the project</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day that the project must start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick Off</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Hours_Sold__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours_Sold__c</fullName>
    <description>Sold hours to new clients</description>
    <label>Total Hours Sold</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Required_Role__c/Required_Role__c.object-meta.xml
<CustomObject>
    <label>Required Role</label>
    <nameField>
        <label>Required Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Sold_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Required_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/Resource_Allocation__c.object-meta.xml
<CustomObject>
    <label>Resource Allocation</label>
    <nameField>
        <label>Resource Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/fields/Required_Role__c.field-meta.xml
<CustomField>
    <fullName>Required_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Role</label>
    <referenceTo>Required_Role__c</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Hours</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResourceAllocationControllerTest.cls
@isTest
private  class ResourceAllocationControllerTest {
    @isTest
    static void insertResourceAllocationsTest() {
       User developer = [
            SELECT Id 
            FROM User 
            WHERE LastName='Testing' 
            AND FirstName='Test Dev'
            LIMIT 1];

        Required_Role__c  reqRole= setUpData();
        Map<Object, Object> newMap = new Map<Object, Object>();

        newMap.put('StartDate', '2021-11-22');
        newMap.put('EndDate', '2021-11-24');
        newMap.put('Id', developer.Id);

        List<Map<Object, Object>> listMap = new List<Map<Object, Object>>{newMap};
        
        ResourceAllocationController.insertResourceAllocations(listMap, reqRole.Id);
        Resource_Allocation__c resource = [SELECT Total_Hours__c  FROM Resource_Allocation__c WHERE Required_Role__c =: reqRole.Id];
        System.assertEquals(24, resource.Total_Hours__c);
    }

    //helper
    @TestSetup
    static void makeUserData(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        UserRole devId = [SELECT Id FROM UserRole WHERE Name='Developer' LIMIT 1];
        User dev = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            FirstName='Test Dev',
            LastName='Testing', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            UserRoleId= devId.Id,
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testdevkaiken@testorg.com'
            );

        insert dev;
    }

    private static Required_Role__c  setUpData(){
        Account acc = new Account(Name = 'TestAcc');
        insert acc;
        
        Opportunity opp = new Opportunity(
            Name = 'testOpp', 
            AccountId= acc.Id, 
            Project_Manager__c = [
                SELECT Id 
                FROM User 
                WHERE FirstName='Agustin' 
                AND LastName='Perdomo'
                LIMIT 1].Id,
            StageName='Negotiation/Review',
            CloseDate= Date.today().addDays(40)
        );
        insert opp;
        
    //project
    Project__c newProject = new Project__c(
        Opportunity__c = opp.Id,
        Account__c = opp.AccountId,
        Start_Date__c = date.newInstance(2021,11,15),
        End_Date__c = date.newInstance(2021,11,15).addDays(90),
        Total_Hours_Sold__c = 100,
        Status__c = 'Pre Kick Off'
        );
    insert newProject;

    //req roles
    Required_Role__c newReqRoles =
        new Required_Role__c(
        Project__c = newProject.Id,
        Quantity__c = 100,
        Name='Developers',
        Role__c = 'Developer'
        );

        insert newReqRoles;
        return newReqRoles;
}
}