force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Manager in charge of the opportunity</description>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The deadline of the project</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day that the project must start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick Off</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Hours_Sold__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours_Sold__c</fullName>
    <description>Sold hours to new clients</description>
    <label>Total Hours Sold</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Required_Role__c/Required_Role__c.object-meta.xml
<CustomObject>
    <label>Required Role</label>
    <nameField>
        <label>Required Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Sold_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Required_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/Resource_Allocation__c.object-meta.xml
<CustomObject>
    <label>Resource Allocation</label>
    <nameField>
        <label>Resource Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/fields/Required_Role__c.field-meta.xml
<CustomField>
    <fullName>Required_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Role</label>
    <referenceTo>Required_Role__c</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Resources__c.field-meta.xml
<CustomField>
    <fullName>Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ResourceAllocationHelperTest.cls
@isTest
public with sharing class ResourceAllocationHelperTest {
    @isTest
    static void onbeforeInsertTest() {
        Account acc = new Account(Name = 'TestAcc');
        insert acc;
        
        Opportunity opp = new Opportunity(Name = 'testOpp', 
                                          AccountId= acc.Id, 
                                          Project_Manager__c = [
                                              SELECT Id 
                                              FROM User 
                                              WHERE FirstName='Agustin' 
                                              AND LastName='Perdomo'
                                              LIMIT 1].Id,
                                          StageName='Negotiation/Review',
                                          CloseDate= Date.today().addDays(5));
        insert opp;
        Date today = Date.today().addDays(10);
        Project__c newProject = new Project__c(
            Opportunity__c = opp.Id,
            Account__c = opp.AccountId,
            Start_Date__c = today,
            End_Date__c = today.addDays(90),
            Total_Hours_Sold__c = 300,
            Status__c = 'Pre Kick Off'
        );
        insert newProject;
        //req roles
        List<Required_Role__c> newReqRoles = new List<Required_Role__c>{
            new Required_Role__c(
                Project__c = newProject.Id,
                Quantity__c = 100,
                Name='Developers',
                Role__c = 'Developer'
            ),
                new Required_Role__c(
                    Project__c = newProject.Id,
                    Quantity__c = 100,
                    Name='Architects',
                    Role__c = 'Architect'
                ),
                new Required_Role__c(
                    Project__c = newProject.Id,
                    Quantity__c = 100,
                    Name='Consultants',
                    Role__c = 'Consultant'
                )
                };
                    
                    insert newReqRoles;
        
        List<Resource_allocation__c> newResourcesDataTest = new List<Resource_allocation__c>();     
        
        // Una alocación de recursos con fechas que van con el proyecto
        Resource_allocation__c resourceTestYes = new Resource_allocation__c();
        resourceTestYes.StartDate__c = today.addDays(11);
        resourceTestYes.EndDate__c =today.addDays(12);
        resourceTestYes.Required_Role__c = newReqRoles.get(0).Id;
        
        //Alocación con fechas menores a las del proyecto
        Resource_allocation__c resourceTestNo1= new Resource_allocation__c();
        resourceTestNo1.StartDate__c = today.addDays(9);
        resourceTestNo1.EndDate__c = today.addDays(11);
        resourceTestNo1.Required_Role__c = newReqRoles.get(0).Id;
        
        //Alocación con fechas mayores a las del proyecto
        Resource_allocation__c resourceTestNo2 = new Resource_allocation__c();
        resourceTestNo2.StartDate__c = today.addDays(11);
        resourceTestNo2.EndDate__c = today.addDays(100);
        resourceTestNo2.Required_Role__c = newReqRoles.get(0).Id;
        
        //agrego cada Resource Allocation a mi lista
        //newResourcesDataTest.add(resourceTestYes);
        
        Test.startTest();
        
        //Hago un insert de mi lista para cargar todos los resource allocation en salesforce 
        try {
            newResourcesDataTest.add(resourceTestYes);
            insert newResourcesDataTest; 
        } catch (DMLException e) {
        }
        newResourcesDataTest.clear();
        try {
            newResourcesDataTest.add(resourceTestNo1);
            insert newResourcesDataTest; 
        } catch (DMLException e) {
        }
        newResourcesDataTest.clear();
        
        try {
            newResourcesDataTest.add(resourceTestNo2);
            insert newResourcesDataTest; 
        } catch (DMLException e) {
        }
        
        Test.stopTest();
        
        //Traigo todos los resource allocation de las base de datos
        List<Resource_allocation__c> listOfResourceAllocationFromDb = [            
            SELECT Id, StartDate__c, EndDate__c, Resources__c 
            FROM Resource_Allocation__c ];
        
        System.assertEquals(listOfResourceAllocationFromDb.get(0).Id,resourceTestYes.Id);
        System.assertNotEquals(listOfResourceAllocationFromDb.get(0).Id, resourceTestNo1.Id);
        System.assertNotEquals(listOfResourceAllocationFromDb.get(0).Id, resourceTestNo2.Id);
        
    }
    
}