force-app/main/default/objects/Opportunity/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Manager in charge of the opportunity</description>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The deadline of the project</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The day that the project must start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick Off</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Hours_Sold__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours_Sold__c</fullName>
    <description>Sold hours to new clients</description>
    <label>Total Hours Sold</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Required_Role__c/Required_Role__c.object-meta.xml
<CustomObject>
    <label>Required Role</label>
    <nameField>
        <label>Required Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Required_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Sold_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Required_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/Resource_Allocation__c.object-meta.xml
<CustomObject>
    <label>Resource Allocation</label>
    <nameField>
        <label>Resource Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/fields/Required_Role__c.field-meta.xml
<CustomField>
    <fullName>Required_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Role</label>
    <referenceTo>Required_Role__c</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Resources__c.field-meta.xml
<CustomField>
    <fullName>Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AllocationFilterControllerTest.cls
@isTest
public with sharing class AllocationFilterControllerTest {
    @isTest static void getRequiredRolesTest() {
        Project__c project = setUpData();

        List<Required_Role__c> reqRoles = AllocationFilterController.getRequiredRoles(project.Id);

        System.assertEquals( 3,
        reqRoles.size(),
        'There must be at least 3 required roles'
        );
    }

    @isTest static void findUsersWithRequiredRolesTest() {
        Project__c project = setUpData();
        User consulUser = [
            SELECT FirstName, LastName, UserRole.Name
            FROM User 
            WHERE FirstName = 'Test Consul' 
            AND LastName='Testing' 
            LIMIT 1];
        User devUser = [
            SELECT FirstName, LastName, UserRole.Name
            FROM User 
            WHERE FirstName = 'Test Dev' 
            AND LastName='Testing' 
            LIMIT 1];
        System.debug('USER' + devUser);
        User archUser = [
            SELECT FirstName, LastName, UserRole.Name
            FROM User 
            WHERE FirstName = 'Test Arch' 
            AND LastName='Testing' 
            LIMIT 1];

        List<User> devs = AllocationFilterController.findUsersWithRequiredRoles('Developer');
        List<User> arch = AllocationFilterController.findUsersWithRequiredRoles('Architect');
        List<User> consul = AllocationFilterController.findUsersWithRequiredRoles('Consultant');

        System.assertEquals(true,
        devs.contains(devUser),
        'Devs list must have in their users the dev test user'
        );
        System.assertEquals( true,
        arch.contains(archUser),
        'Arch list must have in their users the architect test user'
        );
        System.assertEquals( true,
        consul.contains(consulUser),
        'Consul list must have in their users the consul test user'
        );

    }

    @isTest static void checkAllocatedResourcesTest() {
       Project__c project = setUpData();

        List<User> devs = AllocationFilterController.checkAllocatedResources(project.Id, 'Developer');
        List<User> arch = AllocationFilterController.checkAllocatedResources(project.Id, 'Architect');
        List<User> consul = AllocationFilterController.checkAllocatedResources(project.Id, 'Consultant');
        User consulUser = [
            SELECT FirstName, LastName, UserRole.Name
            FROM User 
            WHERE FirstName = 'Test Consul' 
            AND LastName='Testing' 
            LIMIT 1];

        User devUser = [
            SELECT FirstName, LastName, UserRole.Name
            FROM User 
            WHERE FirstName = 'Test Dev' 
            AND LastName='Testing' 
            LIMIT 1];

        User archUser = [
            SELECT FirstName, LastName, UserRole.Name
            FROM User 
            WHERE FirstName = 'Test Arch' 
            AND LastName='Testing' 
            LIMIT 1];
        
         System.assertEquals(true,
        devs.contains(devUser),
        'Devs list must have in their users the dev test user'
        );
        System.assertEquals( true,
        arch.contains(archUser),
        'Arch list must have in their users the architect test user'
        );
        System.assertEquals( false,
        consul.contains(consulUser),
        'Evaristo Miller is allocated, he shouldn\'\t be in the available users'
        );

    }

    //helper
     @testSetUp
    private static void setUpUserData(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        UserRole devId = [SELECT Id FROM UserRole WHERE Name='Developer' LIMIT 1];
        UserRole archId = [SELECT Id FROM UserRole WHERE Name='Architect' LIMIT 1];
        UserRole consulId = [SELECT Id FROM UserRole WHERE Name='Consultant' LIMIT 1];
        
        
        List<User> users = new List<User>();
        User dev = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            FirstName='Test Dev',
            LastName='Testing', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            UserRoleId= devId.Id,
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testdevkaiken@testorg.com'
        );
        users.add(dev);

        User arch = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            FirstNAme='Test Arch',
            LastName='Testing', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            UserRoleId=archId.Id,
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testarchkaiken@testorg.com'
        );
        users.add(arch);

        User consul = new User(
            Alias = 'standt', 
            Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', 
            FirstNAme='Test Consul',
            LastName='Testing', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            UserRoleId=consulId.Id,
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='testconsulkaiken@testorg.com'
        );
        users.add(consul);

        insert users;
    }
    
    private static Project__c setUpData(){
        Account acc = new Account(Name = 'TestAcc');
        insert acc;
        
        Opportunity opp = new Opportunity(
            Name = 'testOpp', 
            AccountId= acc.Id, 
            Project_Manager__c = [
                SELECT Id 
                FROM User 
                WHERE FirstName='Agustin' 
                AND LastName='Perdomo'
                LIMIT 1].Id,
            StageName='Negotiation/Review',
            CloseDate= Date.today().addDays(5)
        );
        insert opp;
        

        Date today = Date.today().addDays(10);
        //project
        Project__c newProject = new Project__c(
            Name='Test Project',
            Opportunity__c = opp.Id,
            Account__c = opp.AccountId,
            Start_Date__c = today,
            End_Date__c = today.addDays(90),
            Total_Hours_Sold__c = 300,
            Status__c = 'Pre Kick Off'
            );
        insert newProject;
        //req roles
        List<Required_Role__c> newReqRoles = new List<Required_Role__c>{
            new Required_Role__c(
            Project__c = newProject.Id,
            Quantity__c = 100,
            Name='Developers',
            Role__c = 'Developer'
            ),
            new Required_Role__c(
            Project__c = newProject.Id,
            Quantity__c = 100,
            Name='Architects',
            Role__c = 'Architect'
            ),
            new Required_Role__c(
            Project__c = newProject.Id,
            Quantity__c = 100,
            Name='Consultants',
            Role__c = 'Consultant'
            )
        };

        insert newReqRoles;

        Required_Role__c consulReqRole = [
            SELECT Id 
            FROM Required_Role__c 
            WHERE Project__c =: newProject.Id 
            AND Name = 'Consultants' 
            LIMIT 1];
        
		User consul = [
            SELECT Id 
            FROM User 
            WHERE FirstName = 'Test Consul' 
            AND LastName='Testing' 
            LIMIT 1];
        
       	Resource_Allocation__c newResourceAlloc = new Resource_Allocation__c(
            Name='Evaristo Consul Allocation',
         	Resources__c= consul.Id,
         	Required_Role__c = consulReqRole.Id,
         	StartDate__c = today.addDays(15),
          	EndDate__c = today.addDays(25)
        );
        
        insert newResourceAlloc;

        return newProject;
    }
}