force-app/main/default/objects/Required_Role__c/Required_Role__c.object-meta.xml
<CustomObject>
    <label>Required Role</label>
    <nameField>
        <label>Required Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/Resource_Allocation__c.object-meta.xml
<CustomObject>
    <label>Resource Allocation</label>
    <nameField>
        <label>Resource Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Allocation__c/fields/Required_Role__c.field-meta.xml
<CustomField>
    <fullName>Required_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Role</label>
    <referenceTo>Required_Role__c</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Resources__c.field-meta.xml
<CustomField>
    <fullName>Resources__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourcesInPojects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Allocation__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Hours</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResourceAllocationController.cls
public with sharing class ResourceAllocationController {
    @AuraEnabled
    public static void insertResourceAllocations(List<Object> allocationData, Id requiredRoleId) {

        List<Resource_Allocation__c> allocationToInserts = new List<Resource_Allocation__c>();

        for(Object dataMap : allocationData){
            Map<Object, Object> resourceAllocatedData = (Map<Object, Object>)dataMap;
    
            Date start = Date.valueOf((String) resourceAllocatedData.get('StartDate'));
            Date endDate = Date.valueOf((String) resourceAllocatedData.get('EndDate'));

            allocationToInserts.add(new Resource_Allocation__c(
                Resources__c = (Id) resourceAllocatedData.get('Id'),
                Required_Role__c = requiredRoleId,
                StartDate__c = start,
                EndDate__c = endDate,
                Total_Hours__c = HoursAssignment.calculateHours(start, endDate)
            ));
            
        }

        insert allocationToInserts;
    }
}